# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autoconfigure: true
        autowire: true

        # Configure
    _instanceof:
        App\Shared\Domain\Bus\Event\DomainEventSubscriber:
            tags: ['app.domain_event_subscriber']

    # Wire
    App\Shared\:
        resource: '../src/Shared'

    App\EMMS\:
        resource: '../src/EMMS'


    # Tagging
    App\Shared\Infrastructure\Bus\Event\InMemory\InMemorySymfonyEventBus:
        arguments: [!tagged app.domain_event_subscriber]
        lazy: true

    App\Shared\Infrastructure\Bus\Event\DomainEventMapping:
        arguments: [!tagged app.domain_event_subscriber]

    App\Shared\Infrastructure\Bus\Event\DomainEventSubscriberLocator:
        arguments: [!tagged app.domain_event_subscriber]


    # Doctrine filters
    gedmo.listener.timestampable:
        class: Gedmo\Timestampable\TimestampableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]

    gedmo.listener.softdeleteable:
        class: Gedmo\SoftDeleteable\SoftDeleteableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]