nelmio_api_doc:
    documentation:
        info:
            title: EasyMoneyManagementSystem
            description: Core API for EasyMoneyManagementSystem
            version: 1.0.0
    areas:
        path_patterns:
            - ^/api(?!/doc$)
