name: CI

on:
  pull_request:
    branches:
    - development
    - staging
    - main

defaults:
  run:
    working-directory: app

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

      # https://github.com/actions/runner/issues/655
    - name: export env
      uses: cardinalby/export-env-action@v1
      with:
        envFile: 'app/.env.test'

      # Docs: https://github.com/shivammathur/setup-php
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: "8.3.9"
        coverage: xdebug

    - name: Get composer cache directory
      id: composer-cache
      run: echo "::set-output name=dir::$(composer config cache-files-dir)"

    - name: Cache composer dependencies
      uses: actions/cache@v3
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        # Use composer.json for key, if composer.lock is not committed.
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-

    - name: Install Composer dependencies
      run: composer install --no-progress --prefer-dist --optimize-autoloader

    - run: composer lint-fix
    - run: composer phpmd
    - run: composer phpstan